BookApp/Models/Cylinder.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BookApp.Models
{
    public class Cylinder
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [DisplayName("Cylinder Id")]
        public string CylinderId { get; set; }
        [Required]  
        public string Components { get; set; }
        [Required]
        public int Concentration { get; set; }
        [Required]
        public string Unit { get; set; }
        public string? Description { get; set; }
        public DateTime CreatedDateTime { get; set; } = DateTime.Now;
    }
}

BookApp/Models/ErrorViewModel.cs
namespace BookApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookApp/Controllers/CylinderController.cs
using BookApp.Data;
using BookApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookApp.Controllers
{
    public class CylinderController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CylinderController(ApplicationDbContext db)
        {
            _db = db;
        }
    
        public IActionResult Index()
        {
            IEnumerable<Cylinder> objCylinderList = _db.CylinderInventory;
            return View(objCylinderList);
        }

        

        //Get
        public IActionResult Create()
        {
            
            return View();
        }

        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Cylinder obj)
        {
            if (ModelState.IsValid)
            {
                _db.CylinderInventory.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Cylinder added successfully";
                TempData["cylinder"] = obj.Id;
                return RedirectToAction("Index");
            }
            return View(obj);   
        }


        //Get
        public IActionResult Edit(int? id)
        {
            if(id==null || id==0)
            {
                return NotFound();
            }
            var cylinderFromDb = _db.CylinderInventory.Find(id);   
            if (cylinderFromDb==null)
            {
                return NotFound();
            }

            return View(cylinderFromDb);
        }
         
        //Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Cylinder obj)
        {
            if (ModelState.IsValid)
            {
                _db.CylinderInventory.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Cylinder updated successfully";
                TempData["cylinder"] = obj.Id;
                return RedirectToAction("Index");
            }
            return View(obj);
        }



        //Get
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var cylinderFromDb = _db.CylinderInventory.Find(id);
            if (cylinderFromDb == null)
            {
                return NotFound();
            }

            return View(cylinderFromDb);
        }

        //Post
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.CylinderInventory.Find(id);
            if(obj == null)
            {
                       return NotFound();
            }

           
                _db.CylinderInventory.Remove(obj);
                _db.SaveChanges();
            TempData["error"] = "Cylinder deleted";
            return RedirectToAction("Index");
         
          
        }
    }
}

BookApp/Controllers/HomeController.cs
using BookApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BookApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookApp/Views/About/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>About</h1>
<p style="width: 80%">The purpose of this small app is to demonstrate the use of multiple technologies in order to take advantage of the unique capabilities of each technology. VueJs was used to wrap
    the cylinder table allowing for easier manipulation of the DOM while ASP.NET Core with the Entity framework takes care of sending HTTP requests to a SQL database on Azure. The app was then published to 
    AzurePages through Microsoft Visual Studio. 
    <br />
    <br />
    The code for this site is avaliable on my GitHub account here <i class="bi bi-arrow-right"></i> <a target="_blank" href="https://github.com/HDover12/CylinderInventory">GitHub Repository</a>
     <br />
    <br />
    
</p>

BookApp/Views/Cylinder/Create.cshtml
@model Cylinder

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row">
            <h2 class="text-primary p-2">Add Cylinder</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div>
            <label asp-for="CylinderId" class="mb-1"></label>
            <input asp-for="CylinderId" class="form-control"/>
            <span asp-validation-for="CylinderId" class="text-danger"></span>
        </div>
          <div>
            <label asp-for="Components" class="mb-1"></label>
            <input asp-for="Components" class="form-control"/>
            <span asp-validation-for="Components" class="text-danger"></span>
        </div>
         <div>
            <label asp-for="Concentration" class="mb-1"></label>
            <input asp-for="Concentration" class="form-control"/>
            <span asp-validation-for="Concentration" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Unit" class="mb-1"></label>
            <input asp-for="Unit" class="form-control"/>
            <span asp-validation-for="Unit" class="text-danger"></span>
        </div>
          <div>
            <label asp-for="Description" class="mb-1"></label>
            <input asp-for="Description" class="form-control"/>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary mt-3" style="width: 150px">Add Cylinder</button>
        <a asp-controller="Cylinder" asp-action="Index" class="btn btn-secondary mt-3" style="width:150px">Cancel</a>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

BookApp/Views/Cylinder/Delete.cshtml
@model Cylinder

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row">
            <h2 class="text-primary p-2">Delete Cylinder</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div>
            <label asp-for="CylinderId" class="mb-1"></label>
            <input asp-for="CylinderId" class="form-control" disabled/>
            <span asp-validation-for="CylinderId" class="text-danger"></span>
        </div>
          <div>
            <label asp-for="Components" class="mb-1"></label>
            <input asp-for="Components" class="form-control" disabled/>
            <span asp-validation-for="Components" class="text-danger"></span>
        </div>
         <div>
            <label asp-for="Concentration" class="mb-1"></label>
            <input asp-for="Concentration" class="form-control" disabled/>
            <span asp-validation-for="Concentration" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Unit" class="mb-1"></label>
            <input asp-for="Unit" class="form-control" disabled/>
            <span asp-validation-for="Unit" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Description" class="mb-1"></label>
            <input asp-for="Description" class="form-control" disabled/>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-danger mt-3" style="width: 150px">Delete Cylinder</button>
        <a asp-controller="Cylinder" asp-action="Index" class="btn btn-secondary mt-3" style="width:150px">Cancel</a>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

BookApp/Views/Cylinder/Edit.cshtml
@model Cylinder

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row">
            <h2 class="text-primary p-2">Edit Cylinder</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div>
            <label asp-for="CylinderId" class="mb-1"></label>
            <input asp-for="CylinderId" class="form-control"/>
            <span asp-validation-for="CylinderId" class="text-danger"></span>
        </div>
          <div>
            <label asp-for="Components" class="mb-1"></label>
            <input asp-for="Components" class="form-control"/>
            <span asp-validation-for="Components" class="text-danger"></span>
        </div>
         <div>
            <label asp-for="Concentration" class="mb-1"></label>
            <input asp-for="Concentration" class="form-control"/>
            <span asp-validation-for="Concentration" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Unit" class="mb-1"></label>
            <input asp-for="Unit" class="form-control"/>
            <span asp-validation-for="Unit" class="text-danger"></span>
        </div>
         <div>
            <label asp-for="Description" class="mb-1"></label>
            <input asp-for="Description" class="form-control"/>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary mt-3" style="width: 150px">Update Cylinder</button>
        <a asp-controller="Cylinder" asp-action="Index" class="btn btn-secondary mt-3" style="width:150px">Cancel</a>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

BookApp/Views/Cylinder/Index.cshtml
@model IEnumerable<Cylinder>
@{
    ViewData["Title"] = "Index";

}


<partial name="_Notification" />
<form >

</form>

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Cylinder List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Cylinder" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-circle"></i> &nbsp Add a Cylinder</a>
        </div>
    </div>
    <br />
 <div id="vueApp">
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                Cylinder Id
            </th>
            <th>
                Component(s)
            </th>
              <th>
                Concentration
            </th>
            <th>
                Unit
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>    


                  @if(TempData["cylinder"] != null)
                     {
                  
                      if(TempData["cylinder"].ToString() == obj.Id.ToString()) 
                        {
                         <td class="text-primary">
                            <i class="bi bi-caret-right-fill text-primary" ></i>  @obj.CylinderId  <a class="btn btn-link" v-on:click="info(@obj.Id)"><i class="bi bi-info-circle"></i></a> 
                         </td>
                        }
                     else
                        {
                        <td>
                            @obj.CylinderId  <a v-on:click="info(@obj.Id)" class="btn btn-link"><i class="bi bi-info-circle"></i></a> 
                        </td>
                
                        }
                    }
                  else
                    {
                      <td>
                            @obj.CylinderId  <a v-on:click="info(@obj.Id)" class="btn btn-link"><i class="bi bi-info-circle"></i></a> 
                       </td>

                    }

                     <td style="position: relative">
                         @obj.Components
                              <div v-if="infodata == @obj.Id">
                                <div class="card bg-body bg-opactiy-75 border-success" style="width: 18rem; position: absolute; left: -50%; top: -20px">
                                     <div class="card-body text-center">
                                  <h5 class="card-title ">@obj.CylinderId</h5>
                                  <hr />
                                  <p class="card-text">Components: <br />@obj.Components</p>
                                  <p class="card-text">Concentration: <br/> @obj.Concentration @obj.Unit</p>
                                  <p>Description: <br /> @obj.Description</p>
                                  <a v-on:click="info(0)" class="btn btn-primary text-center" style="width: 100%">Close</a>
                                 </div>
                                </div>
                              </div>   
                    </td>
                    <td>
                         @obj.Concentration
                    </td>
                    <td>
                          @obj.Unit
                    </td>
                    <td class="text-end">
                        <div class="btn-group" role="group">
                             <a  style="width: 95px" class="btn btn-primary" asp-controller="Cylinder" asp-action="Edit" asp-route-id="@obj.Id"><i class="bi bi-pencil-square"></i> &nbsp; Edit</a>
                        </div>
                        <div class="btn-group" role="group">
                             <a style="background-color: #B02A37; width: 95px" class="btn btn-danger" asp-controller="Cylinder" asp-action="Delete" asp-route-id="@obj.Id"><i class="bi bi-trash3"></i> &nbsp; Delete</a>
                        </div>
                                                   
                            
                    </td>
                                   
            </tr>
               
        }
    </tbody>
</table>
</div> 


@section scripts 
{
             <script type="text/javascript">
            var app = new Vue({
                el: '#vueApp',
                data: {
                   
                    infodata: 0,
                },
                methods : {
                    info: function(id) {
                        this.infodata = id
                    }
                }
            });
        </script>
}

BookApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class=" text-center" >
    <h1 class="display-4 mt-4">Welcome</h1>
    <p style="width: 60%; margin: 0 auto" > Welcome to my example inventory app. This app contains a list of gas cylinders, their contents and concentrations. The data listed herein is for demonstration purposes only does not reflect any real cylinders or inventory

    </p>
    <br />
    <a asp-controller="Cylinder" asp-action="Index" class="btn btn-primary">Go to Cylinder List</a>
</div>

BookApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cylinder Inventory</title>
    <link rel="stylesheet" href="~/css/bootswatch.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="nav nav-tabs navbar navbar-expand-lg navbar-dark bg-dark ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Cylinder Inventory</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" asp-area="" asp-controller="Cylinder" asp-action="Index">Cylinders</a>
        </li>
         <li class="nav-item">
        <a class="nav-link" asp-area="" asp-controller="About" asp-action="Index">About</a>
        </li>
       
   @*     <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>*@
      </ul>
      @*<form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>*@
    </div>
  </div>
</nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <span class="container">
             Cylinder Inventory 
        </span>
        <span class="text-right"> <a target="_blank" href="https://github.com/HDover12">Coded by: Hannah Dover &nbsp;<i class="bi bi-github"></i></a></span>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
     <script src="https://cdn.jsdelivr.net/npm/vue@2.5.22/dist/vue.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookApp/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">
                toastr.success('@TempData["success"]')

        </script>
}


@if (TempData["error"] != null)
{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
            <script type="text/javascript">
                    toastr.error('@TempData["error"]')
            </script>
}